### ISSUE TITLE
/apispec_1.json invalid when creating client library

### ISSUE THREAD

**Issue by Phlogi** [4ch1m/pixoo-rest#8]
I want to create a python client based on the swagger spec:

```

swagger_to_py_client.py \                                                                                         
                                                    --swagger_path ./apispec_1.json \
                                                    --outpath ./pixoo-rest-client
Traceback (most recent call last):
  File "/Users/Phlogi/Downloads/docker_playground/pixoo/pixoo-venv/bin/swagger_to_py_client.py", line 33, in <module>
    sys.exit(load_entry_point('swagger-to==5.0.0', 'console_scripts', 'swagger_to_py_client.py')())
  File "/Users/Phlogi/Downloads/docker_playground/pixoo/pixoo-venv/lib/python3.10/site-packages/swagger_to/bin/swagger_to_py_client.py", line 34, in main
    raise AssertionError("Errors in {}:\n{}".format(swagger_path, "\n".join(errs)))
AssertionError: Errors in apispec_1.json:
"paths"/"/brightness/{percentage}"/"put"/"parameters"/0:RawDict([('default', 85), ('description', 'Percentage value of display brightness.'), ('in', 'path'), ('maximum', 100), ('minimum', '0'), ('name', 'percentage'), ('required', True), ('type', 'integer')]) is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['put']['properties']['parameters']['items']:
    {'oneOf': [{'$ref': '#/definitions/parameter'},
               {'$ref': '#/definitions/jsonReference'}]}

On instance['paths']['/brightness/{percentage}']['put']['parameters'][0]:
    RawDict([('default', 85),
             ('description', 'Percentage value of display brightness.'),
             ('in', 'path'),
             ('maximum', 100),
             ('minimum', '0'),
             ('name', 'percentage'),
             ('required', True),
             ('type', 'integer')])

We used the JSON schema of OpenAPI 2 from: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/88cd94419e117b154b67b834fa8e471bb98bd346/schemas/v2.0/schema.json
```

**Comment by 4ch1m** [comment]
I'm afraid I can't help you with that.
The API-specification is being auto-generated with [Flasgger](https://github.com/flasgger/flasgger).
Maybe the folks over there can help you with that.
If there's anything misconfigured in _pixoo-rest_, please let me know.
Thanks.
